### PR TITLE
Feat: column toggle popup

### PR DESCRIPTION
**Pull request by Muhammad-Arsalan31**
Closes 

## Description

Added new feature  Toggle columns of table

## Current Tasks

- [x] toggle All Columns
- [x] Toggle single column

## Live Demo Link

image

### CODE REVIEW

**Comment by Muhammad-Arsalan31** [comment]
Hi, I know the pull request has merge conflicts and I am trying to resolve the conflicts by using github resolve merge conflicts option but the problem I am facing is that the github resolve conflicts panel for some reason is not loading the files and get stuck. How can I fix this.

Also let me know if this feature will be merged or not because I have seen the features list on readme and this is not planmed. I thought its a cool feature so I made a pull request

**Comment by Kuechlin** [comment]
Hey,
Column ordering is on the road map, for me this includes column toggling, but i am still not quite sure what will be the best user experiences for this element.
Also try using the internal table state with  `table.getState` and `table.setState` instead of creating a new one with `useState`.

**Comment by Muhammad-Arsalan31** [comment]
> 

The toggle popup that  I build was inspired by elastic UI https://elastic.github.io/eui/#/tabular-content/data-grid-schema-columns
the best use case I can think of for column ordering and toggling is that sometimes the table has many horizontal columns and we don't want to view or those columns are less important and get in the way e.g
image

also, I get your point for using the table state and not initializing one another state I will fix this. should I make a new PR for that because  I cannot merge conflicts in this one?

**Comment by Kuechlin** [comment]
yes make a new pr, there are some breaking changes since you opened this pr.

**Pull request closed without merging**
